
# SEO settings
title: Today I Learned - Codinfox
stylished_title: Random <span>Thoughts</span>
description: "Technology ramblings and my day to day learnings."
keywords: "web, coding, cloud computing, azure, angular, angularjs, design, architecture, blog"
url: http://chandermani.github.io
baseurl: ""

google_analytics: UA-98899057-1
disqus_shortname: "chandermani"

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

paginate: 5
paginate_path: "/page/:num/"
comments: true

#source: source
destination: _site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : Chandermani
  thumb    : https://en.gravatar.com/userimage/42626876/ff31b74f207c61cc9d2d1d9196fd0080.jpg?size=120
  email    : cmyworld@gmail.com
  url      : http://chandermani.github.io
  github   : http://github.com/chandermani
  twitter  : http://twitter.com/cmyworld
#  facebook : http://facebook.com/fernando.dev
  linkedin : http://linkedin.com/in/chandermani

# social settings
# og_locale: "pt_BR"
# twitter_card: "summary_large_image"
# twitter_site: "@nandomoreirame"

project:
    repo: https://github.com/chandermani/TIL
    name: TIL
    author: Chandermani

gems:
  - jekyll-paginate

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
